/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of ErrorResponse
 */
interface ErrorResponse {
  /** A message describing the error */
  message?: string;
  /** HTTP status code */
  status?: number;
  /** Optional: Field-specific validation errors */
  field_errors?: Record<string, string | null> | null;
  additionalProperties?: Record<string, unknown>;
}

export class ErrorResponseError extends ApiError<ErrorResponse> {}
