/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Chat, chatSchema } from '../models/chat';
import { ChatResponseEx, chatResponseExSchema } from '../models/chatResponseEx';
import { BaseController } from './baseController';
import { ErrorResponseError } from '../errors/errorResponseError';

export class ChatController extends BaseController {
  /**
   * This endpoint creates a new chat interaction with our AI Models.
   *
   * @param body
   * @return Response from the API call
   */
  async chat(
    body: Chat,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ChatResponseEx>> {
    const req = this.createRequest('POST', '/chat');
    const mapped = req.prepareArgs({ body: [body, chatSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      ErrorResponseError,
      'Bad request, read again our documentation or contact support for guidance.'
    );
    req.throwOn(
      401,
      ErrorResponseError,
      'Not authorized, check our OAuth2 doc.'
    );
    req.throwOn(
      500,
      ErrorResponseError,
      'Internal error, if this error persist, please contact support.'
    );
    req.authenticate([{ oauth2: true }]);
    return req.callAsJson(chatResponseExSchema, requestOptions);
  }
}
