/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Embed, embedSchema } from '../models/embed';
import {
  EmbedResponseEx,
  embedResponseExSchema,
} from '../models/embedResponseEx';
import { BaseController } from './baseController';
import { ErrorResponseError } from '../errors/errorResponseError';

export class EmbedsController extends BaseController {
  /**
   * This endpoint creates a new embed for training your custom AI Models.
   *
   * @param body
   * @return Response from the API call
   */
  async embed(
    body: Embed,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<EmbedResponseEx>> {
    const req = this.createRequest('POST', '/embed');
    const mapped = req.prepareArgs({ body: [body, embedSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      ErrorResponseError,
      'Bad request, read again our documentation or contact support for guidance.'
    );
    req.throwOn(
      401,
      ErrorResponseError,
      'Not authorized, check our OAuth2 doc.'
    );
    req.throwOn(
      500,
      ErrorResponseError,
      'Internal error, if this error persist, please contact support.'
    );
    req.authenticate([{ oauth2: true }]);
    return req.callAsJson(embedResponseExSchema, requestOptions);
  }
}
