/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Chat, chatSchema } from '../models/chat';
import { TotalUsageEx, totalUsageExSchema } from '../models/totalUsageEx';
import {
  UsageCalculationEx,
  usageCalculationExSchema,
} from '../models/usageCalculationEx';
import { BaseController } from './baseController';
import { ErrorResponseError } from '../errors/errorResponseError';

export class UsageController extends BaseController {
  /**
   * This endpoint allows you to calculate the usage, so you get an idea of the amount of tokens that
   * will be consumed.
   *
   * @param body
   * @return Response from the API call
   */
  async calculateTokens(
    body: Chat,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsageCalculationEx>> {
    const req = this.createRequest('POST', '/usage/tokenize');
    const mapped = req.prepareArgs({ body: [body, chatSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      ErrorResponseError,
      'Bad request, read again our documentation or contact support for guidance.'
    );
    req.throwOn(
      401,
      ErrorResponseError,
      'Not authorized, check our OAuth2 doc.'
    );
    req.throwOn(
      500,
      ErrorResponseError,
      'Internal error, if this error persist, please contact support.'
    );
    req.authenticate([{ oauth2: true }]);
    return req.callAsJson(usageCalculationExSchema, requestOptions);
  }

  /**
   * This endpoint calculates the amount of tokens used by the user in the given month.
   *
   * @return Response from the API call
   */
  async totalUsage(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TotalUsageEx>> {
    const req = this.createRequest('GET', '/usage/totals');
    req.throwOn(
      400,
      ErrorResponseError,
      'Bad request, read again our documentation or contact support for guidance.'
    );
    req.throwOn(
      401,
      ErrorResponseError,
      'Not authorized, check our OAuth2 doc.'
    );
    req.throwOn(
      500,
      ErrorResponseError,
      'Internal error, if this error persist, please contact support.'
    );
    req.authenticate([{ oauth2: true }]);
    return req.callAsJson(totalUsageExSchema, requestOptions);
  }
}
