/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { ContentEx, contentExSchema } from './contentEx';

export interface Chat {
  /** Model name */
  model: string;
  /** Request content */
  content: ContentEx[];
  /** If you want to keep context between request, otherwise leave it empty, you get one with every chat you create. */
  chatId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const chatSchema: Schema<Chat> = typedExpandoObject(
  {
    model: ['model', string()],
    content: ['content', array(lazy(() => contentExSchema))],
    chatId: ['chatId', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
