/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { InlineDataEx, inlineDataExSchema } from './inlineDataEx';

/** Request content */
export interface ContentEx {
  /** Text is the task you want the AI to solve. */
  text: string;
  /** Input Reference is the name of the file, if you're request is from a type other than text, and it's required for most types. It has to contain the same name as the file attached in the request. */
  inlineData?: InlineDataEx;
  additionalProperties?: Record<string, unknown>;
}

export const contentExSchema: Schema<ContentEx> = typedExpandoObject(
  {
    text: ['text', string()],
    inlineData: ['inlineData', optional(lazy(() => inlineDataExSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
