/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { UsageEx, usageExSchema } from './usageEx';

export interface EmbedResponseEx {
  /** Embed id */
  id?: string;
  /** This is the token usage result of your request */
  usage?: UsageEx;
  additionalProperties?: Record<string, unknown>;
}

export const embedResponseExSchema: Schema<EmbedResponseEx> = typedExpandoObject(
  {
    id: ['id', optional(string())],
    usage: ['usage', optional(lazy(() => usageExSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
