/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';
import { ContentEx, contentExSchema } from './contentEx';

export interface Embed {
  /** Model name */
  model: string;
  /** Request content */
  content: ContentEx[];
  /** The purpose of the embed, it could be 'search_document', 'search_query', 'classification', o 'clustering'. */
  purpose: string;
  additionalProperties?: Record<string, unknown>;
}

export const embedSchema: Schema<Embed> = typedExpandoObject(
  {
    model: ['model', string()],
    content: ['content', array(lazy(() => contentExSchema))],
    purpose: ['purpose', string()],
  },
  'additionalProperties',
  optional(unknown())
);
