/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Input Reference is the name of the file, if you're request is from a type other than text, and it's required for most types. It has to contain the same name as the file attached in the request. */
export interface InlineDataEx {
  mimeType?: string;
  data?: string;
  additionalProperties?: Record<string, unknown>;
}

export const inlineDataExSchema: Schema<InlineDataEx> = typedExpandoObject(
  {
    mimeType: ['mimeType', optional(string())],
    data: ['data', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
