/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface ModelEx {
  /** Model Id */
  id?: string;
  /** Model name */
  name: string;
  /** Model type of content generation and processing */
  type: string;
  /** Brief description of the model */
  description: string;
  /** Indicates whether is a custom model created by you or not */
  proprietary?: boolean;
  /** Base model name, if it was created from another model */
  baseModel?: string;
  /** Base model id, if it was created from another model */
  baseModelId?: string;
  /** Creation date */
  createdAt?: string;
  /** Last time it was updated */
  updatedAt?: string;
  additionalProperties?: Record<string, unknown>;
}

export const modelExSchema: Schema<ModelEx> = typedExpandoObject(
  {
    id: ['id', optional(string())],
    name: ['name', string()],
    type: ['type', string()],
    description: ['description', string()],
    proprietary: ['proprietary', optional(boolean())],
    baseModel: ['baseModel', optional(string())],
    baseModelId: ['baseModelId', optional(string())],
    createdAt: ['createdAt', optional(string())],
    updatedAt: ['updatedAt', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
