/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { ModelEx, modelExSchema } from './modelEx';

export interface PaginatedResponseExListModelEx {
  page?: number;
  size?: number;
  data?: ModelEx[];
  additionalProperties?: Record<string, unknown>;
}

export const paginatedResponseExListModelExSchema: Schema<PaginatedResponseExListModelEx> = typedExpandoObject(
  {
    page: ['page', optional(number())],
    size: ['size', optional(number())],
    data: ['data', optional(array(lazy(() => modelExSchema)))],
  },
  'additionalProperties',
  optional(unknown())
);
