/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';

/** Tokens used */
export interface TokensEx {
  /** Number of tokens of the request input */
  inputTokens?: number;
  /** Number of tokens of the response output */
  outputTokens?: number;
  additionalProperties?: Record<string, unknown>;
}

export const tokensExSchema: Schema<TokensEx> = typedExpandoObject(
  {
    inputTokens: ['inputTokens', optional(number())],
    outputTokens: ['outputTokens', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
