/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface TotalUsageEx {
  /** Total Input Tokens used for this month */
  totalInput?: bigint;
  /** Total Ouput Tokens used for this month */
  totalOutput?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const totalUsageExSchema: Schema<TotalUsageEx> = typedExpandoObject(
  {
    totalInput: ['totalInput', optional(bigint())],
    totalOutput: ['totalOutput', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
