/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';
import { TokensEx, tokensExSchema } from './tokensEx';

/** This is the token usage result of your request */
export interface UsageEx {
  /** Tokens used */
  billedTokens?: TokensEx;
  /** Tokens used */
  usedTokens?: TokensEx;
  additionalProperties?: Record<string, unknown>;
}

export const usageExSchema: Schema<UsageEx> = typedExpandoObject(
  {
    billedTokens: ['billedTokens', optional(lazy(() => tokensExSchema))],
    usedTokens: ['usedTokens', optional(lazy(() => tokensExSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
