/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema';

export interface UsageCalculationEx {
  /** Estimated tokens for your request */
  estimatedTokens?: number;
  additionalProperties?: Record<string, unknown>;
}

export const usageCalculationExSchema: Schema<UsageCalculationEx> = typedExpandoObject(
  { estimatedTokens: ['estimatedTokens', optional(number())] },
  'additionalProperties',
  optional(unknown())
);
