/**
 * Cuadra AILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { AuthorizationCodeAuthManager } from './authorizationCodeAuthManager';
import { HttpClientOptions } from './clientAdapter';
import { PartialLoggingOptions } from './core';
import { OauthToken } from './models/oauthToken';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  authorizationCodeAuthCredentials?: {
    oauthClientId: string;
    oauthClientSecret: string;
    oauthRedirectUri: string;
    oauthToken?: OauthToken;
    oauthTokenProvider?: (
      lastOAuthToken: OauthToken | undefined,
      authManager: AuthorizationCodeAuthManager
    ) => Promise<OauthToken>;
    oauthOnTokenUpdate?: (token: OauthToken) => void;
    oauthClockSkew?: number;
  };
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
  logging?: PartialLoggingOptions;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
}
